#!/usr/bin/env sh

/usr/local/bin/limelight -m config width 1
/usr/local/bin/limelight -m config radius 6
/usr/local/bin/limelight -m config placement interior
/usr/local/bin/limelight -m config active_color 0xFFFFD119
/usr/local/bin/limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
