#!/usr/bin/env sh

limelight -m config width 1
limelight -m config radius 5
limelight -m config placement exterior
limelight -m config active_color 0xFFFFD119
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
