#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
# first space floating
yabai -m space 1 --layout float
yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   2

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^BIG-IP Edge Client$" manage=off
yabai -m rule --add app="^Citrix Workspace$" manage=off
# Zoom - main window floating, meetings managed
yabai -m rule --add app="^zoom\.us$" title!="^Zoom Meeting$" manage=off
# Eclipse - float all modals
yabai -m rule --add app="^Eclipse$" title!="^.*Eclipse IDE$" manage=off
# SQL developer - float all modals
yabai -m rule --add app="^Oracle SQL Developer$" title!="^Oracle SQL Developer.*$" manage=off

# bitbar integration
yabai -m signal --add event=space_changed action="$HOME/.bin/yabai/spaceEvent.sh"
yabai -m signal --add event=display_added action="$HOME/.bin/yabai/spaceEvent.sh"
yabai -m signal --add event=display_removed action="$HOME/.bin/yabai/spaceEvent.sh"
yabai -m signal --add event=display_changed action="$HOME/.bin/yabai/spaceEvent.sh"
yabai -m signal --add event=display_moved action="$HOME/.bin/yabai/spaceEvent.sh"
yabai -m signal --add event=mission_control_exit action="$HOME/.bin/yabai/spaceEvent.sh"
yabai -m signal --add event=system_woke action="$HOME/.bin/yabai/spaceEvent.sh"
# add the following if you want window status reporting
#yabai -m signal --add event=window_focused="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
/usr/local/bin/limelight &>/dev/null &

echo "yabai configuration loaded.."

